import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import coffeeStores from "../data/coffee-stores.json";

export async function getStaticProps(context: any) {
  return {
    props: { coffeeStores },
  };
}

console.log(coffeeStores);

const Home: NextPage = (props: any) => {
  console.log("props", props);
  const handleOnBannerBtnClick = () => {
    console.log("hi");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View local Coffee Shops"
          handleOnClick={handleOnBannerBtnClick}
        />
        {coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Stores!</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore: any) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    href={`/coffee-store/${coffeeStore.id}`}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl}
                    className={styles.card}
                  />
                );
              })}
              ;
            </div>
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
