import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";

const Home: NextPage = () => {
  const handleOnBannerBtnClick = () => {
    console.log("hi");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View local Coffee Shops"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.cardLayout}>
          <Card
            href="/coffee-store/1"
            name="card"
            imgUrl={"/static/mesh-gradient.png"}
            className={styles.card}
          />
          <Card
            href="/coffee-store/1"
            name="card"
            imgUrl={"/static/mesh-gradient.png"}
            className={styles.card}
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
