import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import { fetchCoffeeStores } from "../lib/coffee-stores";
import useTrackLocation from "../hooks/use-track-location";

const coffeeStores = await fetchCoffeeStores();

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores,
    },
  };
}

console.log(coffeeStores);

const Home = (props) => {
  console.log("props", props);

  const { handleTrackLocation, latLong, LocationErrorMsg } = useTrackLocation();

  console.log("latLong", latLong);
  console.log({ LocationErrorMsg });
  const handleOnBannerBtnClick = () => {
    console.log("hi");
    handleTrackLocation();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View local Coffee Shops"
          handleOnClick={handleOnBannerBtnClick}
        />
        {coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Melbourne</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.fsq_id}
                    href={`/coffee-store/${coffeeStore.fsq_id}`}
                    name={coffeeStore.name}
                    imgUrl={
                      coffeeStore.imgUrl ||
                      "https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80"
                    }
                    className={styles.card}
                  />
                );
              })}
              ;
            </div>
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
